// <auto-generated />
using System;
using LibraryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220021530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("LibraryManagement.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Best known for the Harry Potter fantasy series.",
                            BirthYear = 1965,
                            FirstName = "J.K.",
                            LastName = "Rowling",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "English novelist known for Nineteen Eighty-Four and Animal Farm.",
                            BirthYear = 1903,
                            FirstName = "George",
                            LastName = "Orwell",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Nobel Prize-winning author known for Beloved and Song of Solomon.",
                            BirthYear = 1931,
                            FirstName = "Toni",
                            LastName = "Morrison",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Nobel laureate, master of magical realism.",
                            BirthYear = 1927,
                            FirstName = "Gabriel García",
                            LastName = "Márquez",
                            Nationality = "Colombian"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "International bestselling author of surrealist fiction.",
                            BirthYear = 1949,
                            FirstName = "Haruki",
                            LastName = "Murakami",
                            Nationality = "Japanese"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Author known for Americanah and Half of a Yellow Sun.",
                            BirthYear = 1977,
                            FirstName = "Chimamanda Ngozi",
                            LastName = "Adichie",
                            Nationality = "Nigerian"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Historian and author of Sapiens.",
                            BirthYear = 1976,
                            FirstName = "Yuval Noah",
                            LastName = "Harari",
                            Nationality = "Israeli"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Prolific author of horror and suspense novels.",
                            BirthYear = 1947,
                            FirstName = "Stephen",
                            LastName = "King",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "The Queen of Crime, creator of Hercule Poirot.",
                            BirthYear = 1890,
                            FirstName = "Agatha",
                            LastName = "Christie",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "Nobel laureate known for minimalist prose.",
                            BirthYear = 1899,
                            FirstName = "Ernest",
                            LastName = "Hemingway",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 11,
                            Biography = "Regency-era novelist known for Pride and Prejudice.",
                            BirthYear = 1775,
                            FirstName = "Jane",
                            LastName = "Austen",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 12,
                            Biography = "Russian novelist known for Crime and Punishment.",
                            BirthYear = 1821,
                            FirstName = "Fyodor",
                            LastName = "Dostoevsky",
                            Nationality = "Russian"
                        },
                        new
                        {
                            Id = 13,
                            Biography = "Author of War and Peace and Anna Karenina.",
                            BirthYear = 1828,
                            FirstName = "Leo",
                            LastName = "Tolstoy",
                            Nationality = "Russian"
                        },
                        new
                        {
                            Id = 14,
                            Biography = "Poet and memoirist known for I Know Why the Caged Bird Sings.",
                            BirthYear = 1928,
                            FirstName = "Maya",
                            LastName = "Angelou",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 15,
                            Biography = "Nobel laureate, author of The Remains of the Day.",
                            BirthYear = 1954,
                            FirstName = "Kazuo",
                            LastName = "Ishiguro",
                            Nationality = "British-Japanese"
                        },
                        new
                        {
                            Id = 16,
                            Biography = "Author of No Country for Old Men and The Road.",
                            BirthYear = 1933,
                            FirstName = "Cormac",
                            LastName = "McCarthy",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 17,
                            Biography = "Canadian author known for The Handmaid's Tale.",
                            BirthYear = 1939,
                            FirstName = "Margaret",
                            LastName = "Atwood",
                            Nationality = "Canadian"
                        },
                        new
                        {
                            Id = 18,
                            Biography = "Author of The Alchemist, sold over 150 million copies worldwide.",
                            BirthYear = 1947,
                            FirstName = "Paulo",
                            LastName = "Coelho",
                            Nationality = "Brazilian"
                        },
                        new
                        {
                            Id = 19,
                            Biography = "Philosopher and author of The Stranger.",
                            BirthYear = 1913,
                            FirstName = "Albert",
                            LastName = "Camus",
                            Nationality = "French-Algerian"
                        },
                        new
                        {
                            Id = 20,
                            Biography = "Science fiction author known for the Dune series.",
                            BirthYear = 1920,
                            FirstName = "Frank",
                            LastName = "Herbert",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 21,
                            Biography = "Pioneer of feminist science fiction.",
                            BirthYear = 1929,
                            FirstName = "Ursula K.",
                            LastName = "Le Guin",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 22,
                            Biography = "Author of American Gods and Good Omens.",
                            BirthYear = 1960,
                            FirstName = "Neil",
                            LastName = "Gaiman",
                            Nationality = "British"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LibraryBranchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LibraryBranchId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            AvailableCopies = 3,
                            Description = "The first book in the Harry Potter series.",
                            Genre = "Fantasy",
                            ISBN = "978-0439708180",
                            LibraryBranchId = 1,
                            PublishedYear = 1997,
                            Publisher = "Bloomsbury",
                            Title = "Harry Potter and the Philosopher's Stone",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            AvailableCopies = 4,
                            Description = "Harry's second year at Hogwarts.",
                            Genre = "Fantasy",
                            ISBN = "978-0439064873",
                            LibraryBranchId = 2,
                            PublishedYear = 1998,
                            Publisher = "Bloomsbury",
                            Title = "Harry Potter and the Chamber of Secrets",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            AvailableCopies = 2,
                            Description = "A chilling dystopian novel about totalitarianism.",
                            Genre = "Dystopian Fiction",
                            ISBN = "978-0451524935",
                            LibraryBranchId = 1,
                            PublishedYear = 1949,
                            Publisher = "Secker & Warburg",
                            Title = "Nineteen Eighty-Four",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            AvailableCopies = 3,
                            Description = "An allegorical novella about the Russian Revolution.",
                            Genre = "Political Satire",
                            ISBN = "978-0451526342",
                            LibraryBranchId = 3,
                            PublishedYear = 1945,
                            Publisher = "Secker & Warburg",
                            Title = "Animal Farm",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            AvailableCopies = 1,
                            Description = "A Pulitzer Prize-winning novel about slavery's aftermath.",
                            Genre = "Historical Fiction",
                            ISBN = "978-1400033416",
                            LibraryBranchId = 1,
                            PublishedYear = 1987,
                            Publisher = "Alfred A. Knopf",
                            Title = "Beloved",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            AvailableCopies = 2,
                            Description = "A landmark of magical realism and world literature.",
                            Genre = "Magical Realism",
                            ISBN = "978-0060883287",
                            LibraryBranchId = 2,
                            PublishedYear = 1967,
                            Publisher = "Harper & Row",
                            Title = "One Hundred Years of Solitude",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            AvailableCopies = 2,
                            Description = "A nostalgic story of loss and sexuality.",
                            Genre = "Literary Fiction",
                            ISBN = "978-0375704024",
                            LibraryBranchId = 4,
                            PublishedYear = 1987,
                            Publisher = "Kodansha",
                            Title = "Norwegian Wood",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 6,
                            AvailableCopies = 3,
                            Description = "A story of identity, race, and love.",
                            Genre = "Contemporary Fiction",
                            ISBN = "978-0307455925",
                            LibraryBranchId = 5,
                            PublishedYear = 2013,
                            Publisher = "Knopf",
                            Title = "Americanah",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 7,
                            AvailableCopies = 2,
                            Description = "A sweeping history of the human species.",
                            Genre = "Non-Fiction",
                            ISBN = "978-0062316097",
                            LibraryBranchId = 1,
                            PublishedYear = 2011,
                            Publisher = "Harper",
                            Title = "Sapiens: A Brief History of Humankind",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 8,
                            AvailableCopies = 3,
                            Description = "A terrifying psychological horror novel.",
                            Genre = "Horror",
                            ISBN = "978-0385121675",
                            LibraryBranchId = 3,
                            PublishedYear = 1977,
                            Publisher = "Doubleday",
                            Title = "The Shining",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 9,
                            AvailableCopies = 2,
                            Description = "Hercule Poirot investigates a murder on a train.",
                            Genre = "Mystery",
                            ISBN = "978-0062693662",
                            LibraryBranchId = 6,
                            PublishedYear = 1934,
                            Publisher = "Collins Crime Club",
                            Title = "Murder on the Orient Express",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 10,
                            AvailableCopies = 2,
                            Description = "A Pulitzer Prize-winning story of perseverance.",
                            Genre = "Literary Fiction",
                            ISBN = "978-0684801223",
                            LibraryBranchId = 7,
                            PublishedYear = 1952,
                            Publisher = "Charles Scribner's Sons",
                            Title = "The Old Man and the Sea",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 11,
                            AvailableCopies = 4,
                            Description = "A classic novel of manners and marriage.",
                            Genre = "Classic Romance",
                            ISBN = "978-0141040349",
                            LibraryBranchId = 8,
                            PublishedYear = 1813,
                            Publisher = "T. Egerton",
                            Title = "Pride and Prejudice",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 12,
                            AvailableCopies = 1,
                            Description = "A study of the criminal mind.",
                            Genre = "Psychological Fiction",
                            ISBN = "978-0140449136",
                            LibraryBranchId = 9,
                            PublishedYear = 1866,
                            Publisher = "The Russian Messenger",
                            Title = "Crime and Punishment",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 13,
                            AvailableCopies = 2,
                            Description = "An epic tale of Russia during the Napoleonic era.",
                            Genre = "Historical Fiction",
                            ISBN = "978-0199232765",
                            LibraryBranchId = 10,
                            PublishedYear = 1869,
                            Publisher = "The Russian Messenger",
                            Title = "War and Peace",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 14,
                            AvailableCopies = 3,
                            Description = "An autobiography of Maya Angelou's early years.",
                            Genre = "Autobiography",
                            ISBN = "978-0345514400",
                            LibraryBranchId = 11,
                            PublishedYear = 1969,
                            Publisher = "Random House",
                            Title = "I Know Why the Caged Bird Sings",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 15,
                            AvailableCopies = 2,
                            Description = "A haunting dystopian novel about cloning.",
                            Genre = "Dystopian Fiction",
                            ISBN = "978-1400078776",
                            LibraryBranchId = 12,
                            PublishedYear = 2005,
                            Publisher = "Faber and Faber",
                            Title = "Never Let Me Go",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 16,
                            AvailableCopies = 2,
                            Description = "A father and son survive in a post-apocalyptic world.",
                            Genre = "Post-Apocalyptic",
                            ISBN = "978-0307387899",
                            LibraryBranchId = 13,
                            PublishedYear = 2006,
                            Publisher = "Alfred A. Knopf",
                            Title = "The Road",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 17,
                            AvailableCopies = 3,
                            Description = "A Canadian dystopian novel about a totalitarian society.",
                            Genre = "Dystopian Fiction",
                            ISBN = "978-0385490818",
                            LibraryBranchId = 1,
                            PublishedYear = 1985,
                            Publisher = "McClelland & Stewart",
                            Title = "The Handmaid's Tale",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 18,
                            AvailableCopies = 4,
                            Description = "A journey of self-discovery and following one's dream.",
                            Genre = "Philosophical Fiction",
                            ISBN = "978-0062315007",
                            LibraryBranchId = 2,
                            PublishedYear = 1988,
                            Publisher = "HarperOne",
                            Title = "The Alchemist",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 19,
                            AvailableCopies = 2,
                            Description = "An exploration of existentialism and absurdism.",
                            Genre = "Philosophical Fiction",
                            ISBN = "978-0679720201",
                            LibraryBranchId = 3,
                            PublishedYear = 1942,
                            Publisher = "Gallimard",
                            Title = "The Stranger",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 20,
                            AvailableCopies = 3,
                            Description = "An epic science fiction saga set in the far future.",
                            Genre = "Science Fiction",
                            ISBN = "978-0441013593",
                            LibraryBranchId = 4,
                            PublishedYear = 1965,
                            Publisher = "Chilton Books",
                            Title = "Dune",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 21,
                            AvailableCopies = 2,
                            Description = "A groundbreaking feminist science fiction novel.",
                            Genre = "Science Fiction",
                            ISBN = "978-0441478125",
                            LibraryBranchId = 5,
                            PublishedYear = 1969,
                            Publisher = "Ace Books",
                            Title = "The Left Hand of Darkness",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 22,
                            AvailableCopies = 3,
                            Description = "A fantasy novel about old gods vs. new American gods.",
                            Genre = "Fantasy",
                            ISBN = "978-0380973651",
                            LibraryBranchId = 6,
                            PublishedYear = 2001,
                            Publisher = "William Morrow",
                            Title = "American Gods",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 5,
                            AvailableCopies = 1,
                            Description = "A surreal parallel narrative.",
                            Genre = "Magical Realism",
                            ISBN = "978-1400079278",
                            LibraryBranchId = 7,
                            PublishedYear = 2002,
                            Publisher = "Shinchosha",
                            Title = "Kafka on the Shore",
                            TotalCopies = 2
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LibraryBranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryBranchId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "101 Oak St, Vancouver",
                            Email = "alice.thompson@email.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Thompson",
                            LibraryBranchId = 1,
                            MemberSince = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "202 Maple Ave, Vancouver",
                            Email = "bob.martinez@email.com",
                            FirstName = "Bob",
                            IsActive = true,
                            LastName = "Martinez",
                            LibraryBranchId = 2,
                            MemberSince = new DateTime(2019, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "303 Pine Rd, Burnaby",
                            Email = "carol.williams@email.com",
                            FirstName = "Carol",
                            IsActive = true,
                            LastName = "Williams",
                            LibraryBranchId = 5,
                            MemberSince = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "404 Cedar Dr, Richmond",
                            Email = "david.chen@email.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Chen",
                            LibraryBranchId = 6,
                            MemberSince = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "505 Birch Blvd, Surrey",
                            Email = "eva.rodriguez@email.com",
                            FirstName = "Eva",
                            IsActive = true,
                            LastName = "Rodriguez",
                            LibraryBranchId = 7,
                            MemberSince = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "606 Spruce St, Vancouver",
                            Email = "frank.lee@email.com",
                            FirstName = "Frank",
                            IsActive = false,
                            LastName = "Lee",
                            LibraryBranchId = 1,
                            MemberSince = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1006"
                        },
                        new
                        {
                            Id = 7,
                            Address = "707 Willow Way, North Vancouver",
                            Email = "grace.kim@email.com",
                            FirstName = "Grace",
                            IsActive = true,
                            LastName = "Kim",
                            LibraryBranchId = 4,
                            MemberSince = new DateTime(2021, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1007"
                        },
                        new
                        {
                            Id = 8,
                            Address = "808 Elm St, Coquitlam",
                            Email = "henry.nguyen@email.com",
                            FirstName = "Henry",
                            IsActive = true,
                            LastName = "Nguyen",
                            LibraryBranchId = 9,
                            MemberSince = new DateTime(2019, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1008"
                        },
                        new
                        {
                            Id = 9,
                            Address = "909 Aspen Ave, Vancouver",
                            Email = "isla.patel@email.com",
                            FirstName = "Isla",
                            IsActive = true,
                            LastName = "Patel",
                            LibraryBranchId = 8,
                            MemberSince = new DateTime(2023, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1009"
                        },
                        new
                        {
                            Id = 10,
                            Address = "1010 Cherry Cres, Vancouver",
                            Email = "james.brown@email.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Brown",
                            LibraryBranchId = 1,
                            MemberSince = new DateTime(2017, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1010"
                        },
                        new
                        {
                            Id = 11,
                            Address = "111 Fir St, Langley",
                            Email = "karen.wilson@email.com",
                            FirstName = "Karen",
                            IsActive = true,
                            LastName = "Wilson",
                            LibraryBranchId = 10,
                            MemberSince = new DateTime(2022, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1011"
                        },
                        new
                        {
                            Id = 12,
                            Address = "222 Alder Rd, New Westminster",
                            Email = "liam.anderson@email.com",
                            FirstName = "Liam",
                            IsActive = true,
                            LastName = "Anderson",
                            LibraryBranchId = 13,
                            MemberSince = new DateTime(2020, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1012"
                        },
                        new
                        {
                            Id = 13,
                            Address = "333 Poplar Pl, Port Moody",
                            Email = "mia.garcia@email.com",
                            FirstName = "Mia",
                            IsActive = true,
                            LastName = "Garcia",
                            LibraryBranchId = 14,
                            MemberSince = new DateTime(2021, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1013"
                        },
                        new
                        {
                            Id = 14,
                            Address = "444 Sycamore St, White Rock",
                            Email = "noah.taylor@email.com",
                            FirstName = "Noah",
                            IsActive = false,
                            LastName = "Taylor",
                            LibraryBranchId = 19,
                            MemberSince = new DateTime(2019, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1014"
                        },
                        new
                        {
                            Id = 15,
                            Address = "555 Magnolia Ave, Delta",
                            Email = "olivia.moore@email.com",
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Moore",
                            LibraryBranchId = 20,
                            MemberSince = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1015"
                        },
                        new
                        {
                            Id = 16,
                            Address = "666 Hickory Rd, Vancouver",
                            Email = "peter.jackson@email.com",
                            FirstName = "Peter",
                            IsActive = true,
                            LastName = "Jackson",
                            LibraryBranchId = 11,
                            MemberSince = new DateTime(2018, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1016"
                        },
                        new
                        {
                            Id = 17,
                            Address = "777 Walnut Way, Maple Ridge",
                            Email = "quinn.davis@email.com",
                            FirstName = "Quinn",
                            IsActive = true,
                            LastName = "Davis",
                            LibraryBranchId = 18,
                            MemberSince = new DateTime(2022, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1017"
                        },
                        new
                        {
                            Id = 18,
                            Address = "888 Juniper St, Vancouver",
                            Email = "rachel.scott@email.com",
                            FirstName = "Rachel",
                            IsActive = true,
                            LastName = "Scott",
                            LibraryBranchId = 3,
                            MemberSince = new DateTime(2020, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1018"
                        },
                        new
                        {
                            Id = 19,
                            Address = "999 Cypress Blvd, Burnaby",
                            Email = "samuel.white@email.com",
                            FirstName = "Samuel",
                            IsActive = true,
                            LastName = "White",
                            LibraryBranchId = 5,
                            MemberSince = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1019"
                        },
                        new
                        {
                            Id = 20,
                            Address = "1111 Redwood Ave, Richmond",
                            Email = "tina.harris@email.com",
                            FirstName = "Tina",
                            IsActive = true,
                            LastName = "Harris",
                            LibraryBranchId = 6,
                            MemberSince = new DateTime(2022, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1020"
                        },
                        new
                        {
                            Id = 21,
                            Address = "1212 Rosewood Rd, Surrey",
                            Email = "uma.clark@email.com",
                            FirstName = "Uma",
                            IsActive = true,
                            LastName = "Clark",
                            LibraryBranchId = 7,
                            MemberSince = new DateTime(2023, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1021"
                        },
                        new
                        {
                            Id = 22,
                            Address = "1313 Larch St, Vancouver",
                            Email = "victor.lewis@email.com",
                            FirstName = "Victor",
                            IsActive = true,
                            LastName = "Lewis",
                            LibraryBranchId = 12,
                            MemberSince = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604-555-1022"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.LibraryBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LibraryBranches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "100 Main Street",
                            BranchName = "Downtown Central Library",
                            City = "Vancouver",
                            Email = "downtown@library.ca",
                            IsOpen = true,
                            ManagerName = "Sarah Johnson",
                            OpeningHours = "Mon-Fri 9am-8pm, Sat-Sun 10am-5pm",
                            Phone = "604-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Address = "250 Robson Street",
                            BranchName = "West End Branch",
                            City = "Vancouver",
                            Email = "westend@library.ca",
                            IsOpen = true,
                            ManagerName = "Michael Chen",
                            OpeningHours = "Mon-Sat 10am-7pm",
                            Phone = "604-555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Address = "515 Kingsway Ave",
                            BranchName = "East Vancouver Branch",
                            City = "Vancouver",
                            Email = "eastvan@library.ca",
                            IsOpen = true,
                            ManagerName = "Priya Patel",
                            OpeningHours = "Mon-Fri 10am-6pm, Sat 10am-4pm",
                            Phone = "604-555-0103"
                        },
                        new
                        {
                            Id = 4,
                            Address = "1 Lonsdale Ave",
                            BranchName = "North Shore Library",
                            City = "North Vancouver",
                            Email = "northshore@library.ca",
                            IsOpen = true,
                            ManagerName = "Robert Wilson",
                            OpeningHours = "Mon-Sun 9am-9pm",
                            Phone = "604-555-0104"
                        },
                        new
                        {
                            Id = 5,
                            Address = "200 Willingdon Ave",
                            BranchName = "Burnaby Central Branch",
                            City = "Burnaby",
                            Email = "burnaby@library.ca",
                            IsOpen = true,
                            ManagerName = "Lisa Nguyen",
                            OpeningHours = "Mon-Fri 9am-7pm, Sat 10am-5pm",
                            Phone = "604-555-0105"
                        },
                        new
                        {
                            Id = 6,
                            Address = "7700 Minoru Blvd",
                            BranchName = "Richmond Branch",
                            City = "Richmond",
                            Email = "richmond@library.ca",
                            IsOpen = true,
                            ManagerName = "David Park",
                            OpeningHours = "Mon-Sat 9am-8pm",
                            Phone = "604-555-0106"
                        },
                        new
                        {
                            Id = 7,
                            Address = "10350 University Dr",
                            BranchName = "Surrey City Centre",
                            City = "Surrey",
                            Email = "surrey@library.ca",
                            IsOpen = true,
                            ManagerName = "Amanda Torres",
                            OpeningHours = "Mon-Sun 10am-8pm",
                            Phone = "604-555-0107"
                        },
                        new
                        {
                            Id = 8,
                            Address = "2425 MacDonald St",
                            BranchName = "Kitsilano Branch",
                            City = "Vancouver",
                            Email = "kits@library.ca",
                            IsOpen = true,
                            ManagerName = "James Murphy",
                            OpeningHours = "Mon-Sat 10am-6pm",
                            Phone = "604-555-0108"
                        },
                        new
                        {
                            Id = 9,
                            Address = "575 Poirier St",
                            BranchName = "Coquitlam Branch",
                            City = "Coquitlam",
                            Email = "coquitlam@library.ca",
                            IsOpen = true,
                            ManagerName = "Helen Zhang",
                            OpeningHours = "Mon-Fri 9am-7pm, Sun 12pm-5pm",
                            Phone = "604-555-0109"
                        },
                        new
                        {
                            Id = 10,
                            Address = "20382 64A Ave",
                            BranchName = "Langley Township Branch",
                            City = "Langley",
                            Email = "langley@library.ca",
                            IsOpen = false,
                            ManagerName = "Kevin Brown",
                            OpeningHours = "Mon-Sat 10am-7pm",
                            Phone = "604-555-0110"
                        },
                        new
                        {
                            Id = 11,
                            Address = "1956 Main Mall",
                            BranchName = "UBC Campus Branch",
                            City = "Vancouver",
                            Email = "ubc@library.ca",
                            IsOpen = true,
                            ManagerName = "Dr. Emily Ross",
                            OpeningHours = "Mon-Sun 8am-10pm",
                            Phone = "604-555-0111"
                        },
                        new
                        {
                            Id = 12,
                            Address = "1 Kingsway",
                            BranchName = "Mount Pleasant Branch",
                            City = "Vancouver",
                            Email = "mtpleasant@library.ca",
                            IsOpen = true,
                            ManagerName = "Carlos Rivera",
                            OpeningHours = "Tue-Sat 10am-6pm",
                            Phone = "604-555-0112"
                        },
                        new
                        {
                            Id = 13,
                            Address = "716 6th Ave",
                            BranchName = "New Westminster Branch",
                            City = "New Westminster",
                            Email = "newwest@library.ca",
                            IsOpen = true,
                            ManagerName = "Sandra Kim",
                            OpeningHours = "Mon-Fri 9am-8pm",
                            Phone = "604-555-0113"
                        },
                        new
                        {
                            Id = 14,
                            Address = "100 Newport Dr",
                            BranchName = "Port Moody Branch",
                            City = "Port Moody",
                            Email = "portmoody@library.ca",
                            IsOpen = true,
                            ManagerName = "Nathan Scott",
                            OpeningHours = "Mon-Sat 10am-7pm",
                            Phone = "604-555-0114"
                        },
                        new
                        {
                            Id = 15,
                            Address = "4111 Moncton St",
                            BranchName = "Steveston Branch",
                            City = "Richmond",
                            Email = "steveston@library.ca",
                            IsOpen = true,
                            ManagerName = "Grace Lee",
                            OpeningHours = "Mon-Sun 10am-5pm",
                            Phone = "604-555-0115"
                        },
                        new
                        {
                            Id = 16,
                            Address = "4515 Dunbar St",
                            BranchName = "Dunbar Branch",
                            City = "Vancouver",
                            Email = "dunbar@library.ca",
                            IsOpen = true,
                            ManagerName = "Frank Mitchell",
                            OpeningHours = "Mon-Sat 9am-6pm",
                            Phone = "604-555-0116"
                        },
                        new
                        {
                            Id = 17,
                            Address = "4885 Capilano Rd",
                            BranchName = "Capilano Branch",
                            City = "North Vancouver",
                            Email = "capilano@library.ca",
                            IsOpen = true,
                            ManagerName = "Maria Garcia",
                            OpeningHours = "Mon-Fri 10am-7pm",
                            Phone = "604-555-0117"
                        },
                        new
                        {
                            Id = 18,
                            Address = "130 - 22470 Dewdney Trunk Rd",
                            BranchName = "Maple Ridge Branch",
                            City = "Maple Ridge",
                            Email = "mapleridge@library.ca",
                            IsOpen = true,
                            ManagerName = "Paul Thompson",
                            OpeningHours = "Mon-Sat 9am-7pm",
                            Phone = "604-555-0118"
                        },
                        new
                        {
                            Id = 19,
                            Address = "15342 Russell Ave",
                            BranchName = "White Rock Branch",
                            City = "White Rock",
                            Email = "whiterock@library.ca",
                            IsOpen = true,
                            ManagerName = "Susan Walker",
                            OpeningHours = "Tue-Sat 10am-6pm",
                            Phone = "604-555-0119"
                        },
                        new
                        {
                            Id = 20,
                            Address = "4695 Clarence Taylor Cres",
                            BranchName = "Delta Branch",
                            City = "Delta",
                            Email = "delta@library.ca",
                            IsOpen = true,
                            ManagerName = "Victor Hernandez",
                            OpeningHours = "Mon-Fri 9am-8pm, Sat 10am-4pm",
                            Phone = "604-555-0120"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.HasOne("LibraryManagement.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.LibraryBranch", "LibraryBranch")
                        .WithMany("Books")
                        .HasForeignKey("LibraryBranchId");

                    b.Navigation("Author");

                    b.Navigation("LibraryBranch");
                });

            modelBuilder.Entity("LibraryManagement.Models.Customer", b =>
                {
                    b.HasOne("LibraryManagement.Models.LibraryBranch", "LibraryBranch")
                        .WithMany("Customers")
                        .HasForeignKey("LibraryBranchId");

                    b.Navigation("LibraryBranch");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagement.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagement.Models.LibraryBranch", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
